In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.shape

(50000, 2)

In [4]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [5]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [7]:
from sklearn.preprocessing import LabelEncoder

encoder=LabelEncoder()

df['sentiment']=encoder.fit_transform(df['sentiment'])
df['sentiment']

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: int64

In [8]:
#.values is used to convert Pandas Series into Numpy Array(which works best with keras)
X=df['review'].values
y=df['sentiment'].values

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [10]:
VOCAB_SIZE=10000
MAX_LEN=200

In [11]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer=Tokenizer(num_words=VOCAB_SIZE)
tokenizer.fit_on_texts(X_train)

In [12]:
X_train_sequence=tokenizer.texts_to_sequences(X_train)
X_test_sequence=tokenizer.texts_to_sequences(X_test)

In [13]:
X_train_pad=pad_sequences(X_train_sequence,maxlen=MAX_LEN)
X_test_pad=pad_sequences(X_test_sequence,maxlen=MAX_LEN)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding

model=Sequential()

model.add(Embedding(input_dim=VOCAB_SIZE,output_dim=64,input_length=MAX_LEN))

model.add(Flatten())

model.add(Dense(64,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\mansi.apet\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
history=model.fit(X_train_pad,y_train,epochs=10,batch_size=32,validation_split=0.1,verbose=1)

Epoch 1/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 18s 17ms/step - accuracy: 0.8195 - loss: 0.3821 - val_accuracy: 0.8809 - val_loss: 0.2833
Epoch 2/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 0.9680 - loss: 0.0938 - val_accuracy: 0.8591 - val_loss: 0.4083
Epoch 3/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 0.9957 - loss: 0.0143 - val_accuracy: 0.8629 - val_loss: 0.5882
Epoch 4/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 0.9992 - loss: 0.0034 - val_accuracy: 0.8617 - val_loss: 0.6667
Epoch 5/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 1.0000 - loss: 7.3021e-04 - val_accuracy: 0.8646 - val_loss: 0.7822
Epoch 6/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 1.0000 - loss: 6.8947e-05 - val_accuracy: 0.8711 - val_loss: 0.8062
Epoch 7/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 1.0000 - loss: 2.6273e-05 - val_accuracy: 0.8714 - val_loss: 0.8277
Epoch 8/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 17s 17ms/step - accuracy: 1.0000 - loss: 1.5218e-05 - val_accuracy: 0.8717 - val_loss: 0.8504
Epoch 9/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 12s 12ms/step - accuracy: 1.0000 - loss: 9.0074e-06 - val_accuracy: 0.8717 - val_loss: 0.8761
Epoch 10/10
985/985 ━━━━━━━━━━━━━━━━━━━━ 15s 15ms/step - accuracy: 1.0000 - loss: 5.9613e-06 - val_accuracy: 0.8683 - val_loss: 0.8993

In [16]:
loss, accuracy=model.evaluate(X_test_pad,y_test)
print("Loss:",loss)
print("Accuracy:",accuracy)

469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8659 - loss: 0.8436
Loss: 0.843626081943512
Accuracy: 0.8658666610717773

In [17]:
y_pred_prob=model.predict(X_test_pad)
y_pred=(y_pred_prob>0.5).astype(int)

469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step

In [18]:
from sklearn.metrics import confusion_matrix,classification_report

cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:",cm)

print("\n Classification Report:",classification_report(y_test,y_pred))

Confusion Matrix: [[6445  966]
 [1046 6543]]

 Classification Report:               precision    recall  f1-score   support

           0       0.86      0.87      0.86      7411
           1       0.87      0.86      0.87      7589

    accuracy                           0.87     15000
   macro avg       0.87      0.87      0.87     15000
weighted avg       0.87      0.87      0.87     15000